'use client'

import { useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { ArrowRight, Check, ChevronDown, ChevronRight, Droplets, Hammer, Menu, Phone, ShieldCheck, Star, X } from 'lucide-react'

const goals = ['Fix drainage', 'Winter patio', 'Spring reservation']
const faqs = [
  ['Can hardscaping and porcelain paving be laid during Glasgow winters?', 'Yes. Hardscaping relies on structural excavation and frost-proof mortar systems, not plant cycles. We use covered working setups to continue installations clean through winter, saving you from spring waitlists.'],
  ['How do you fix heavy Glasgow clay soil drainage issues?', 'We excavate past the clay layer, install geotextile separation membranes, and use a deep MOT Type 1 sub-base engineered specifically for heavy Scottish rainfall.'],
  ['How much does a porcelain patio cost in Bearsden or Newton Mearns?', 'Fully installed porcelain paving with excavation, sub-base preparation, and integrated drainage ranges between £120 and £180 per m².'],
]

function SurveyDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [step, setStep] = useState(1)
  const [goal, setGoal] = useState('')
  const [postcode, setPostcode] = useState('')
  const [form, setForm] = useState({ name: '', email: '', phone: '' })
  const [errors, setErrors] = useState<Record<string, string>>({})
  const [submitted, setSubmitted] = useState(false)
  const close = () => { setStep(1); setGoal(''); setPostcode(''); setForm({ name: '', email: '', phone: '' }); setErrors({}); setSubmitted(false); onClose() }
  if (!open) return null
  const next = () => {
    const nextErrors: Record<string, string> = {}
    if (step === 1 && !goal) nextErrors.goal = 'Choose the project outcome that fits best.'
    if (step === 2 && !/^[A-Z]{1,2}\d[A-Z\d]?\s?\d[A-Z]{2}$/i.test(postcode.trim())) nextErrors.postcode = 'Enter a valid UK postcode.'
    if (step === 3) { if (!form.name.trim()) nextErrors.name = 'Add your name.'; if (!/^\S+@\S+\.\S+$/.test(form.email)) nextErrors.email = 'Enter a valid email.'; if (!form.phone.trim()) nextErrors.phone = 'Add a phone number.' }
    setErrors(nextErrors)
    if (Object.keys(nextErrors).length) return
    if (step < 3) setStep(step + 1); else setSubmitted(true)
  }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-foreground/60 p-0 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-labelledby="survey-title">
    <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} className="relative max-h-[92vh] w-full max-w-xl overflow-y-auto bg-background p-6 shadow-2xl sm:p-10">
      <button onClick={close} className="absolute right-5 top-5 rounded-full p-2 text-muted-foreground hover:bg-muted" aria-label="Close survey"><X size={20} /></button>
      {submitted ? <div className="py-10 text-center"><div className="mx-auto mb-5 flex size-14 items-center justify-center rounded-full bg-primary text-primary-foreground"><Check /></div><p className="eyebrow">Survey request saved locally</p><h2 className="mt-3 font-serif text-4xl text-primary">You&apos;re on the list.</h2><p className="mx-auto mt-4 max-w-sm leading-7 text-muted-foreground">This prototype does not send data yet. In production, your details will be routed to the team with your preferred project goal.</p><button onClick={close} className="mt-8 button-clay">Close <ArrowRight size={16} /></button></div> : <>
        <p className="eyebrow">Fixed-price site survey · Step {step} of 3</p><h2 id="survey-title" className="mt-3 max-w-md font-serif text-4xl leading-tight text-primary">Let&apos;s make your garden work harder.</h2>
        <div className="mt-8 flex gap-2">{[1,2,3].map((n) => <div key={n} className={`h-1 flex-1 ${n <= step ? 'bg-accent' : 'bg-border'}`} />)}</div>
        <div className="mt-8">{step === 1 && <fieldset><legend className="text-lg font-semibold text-foreground">What are you hoping to solve?</legend><div className="mt-4 grid gap-3">{goals.map((item) => <button key={item} onClick={() => setGoal(item)} className={`choice ${goal === item ? 'choice-active' : ''}`}>{item}<ChevronRight size={17} /></button>)}</div>{errors.goal && <p className="mt-2 text-sm text-destructive">{errors.goal}</p>}</fieldset>}
        {step === 2 && <div><label className="text-lg font-semibold" htmlFor="postcode">What&apos;s your postcode?</label><p className="mt-2 text-sm leading-6 text-muted-foreground">We&apos;ll use this to confirm coverage. Bearsden, Newton Mearns, Clarkston and Giffnock are priority areas.</p><input id="postcode" value={postcode} onChange={(e) => setPostcode(e.target.value.toUpperCase())} className="field mt-5" placeholder="e.g. G61 2AB" />{errors.postcode && <p className="mt-2 text-sm text-destructive">{errors.postcode}</p>}</div>}
        {step === 3 && <div><p className="text-lg font-semibold">Where should we send your confirmation?</p><div className="mt-4 grid gap-3">{(['name','email','phone'] as const).map((key) => <div key={key}><label className="sr-only" htmlFor={key}>{key}</label><input id={key} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="field" placeholder={key === 'name' ? 'Your name' : key === 'email' ? 'Email address' : 'Phone number'} />{errors[key] && <p className="mt-1 text-sm text-destructive">{errors[key]}</p>}</div>)}</div><p className="mt-4 text-xs leading-5 text-muted-foreground">By continuing, you agree to be contacted about this survey request. Replace this provisional consent copy before launch.</p></div>}</div>
        <div className="mt-8 flex justify-between gap-3"><button onClick={() => step > 1 ? setStep(step - 1) : close()} className="button-quiet">{step > 1 ? 'Back' : 'Cancel'}</button><button onClick={next} className="button-clay">{step === 3 ? 'Request survey' : 'Continue'} <ArrowRight size={16} /></button></div>
      </>}
    </motion.div>
  </div>
}

function Header({ onSurvey }: { onSurvey: () => void }) { const [menu, setMenu] = useState(false); return <header className="site-header"><a href="#top" className="wordmark"><span className="wordmark-mark">A</span><span>Arden<span className="text-accent"> / </span>Works<small>LANDSCAPE ENGINEERING</small></span></a><nav className="hidden items-center gap-7 md:flex"><a href="#proof">Proof</a><a href="#process">Process</a><a href="#faq">FAQs</a><a href="tel:+441410000000" className="flex items-center gap-2 text-primary"><Phone size={15} /> 0141 000 0000</a></nav><button className="md:hidden" onClick={() => setMenu(!menu)} aria-label="Open menu">{menu ? <X /> : <Menu />}</button>{menu && <div className="absolute left-0 right-0 top-full grid gap-4 border-b border-border bg-background p-6 md:hidden"><a href="#proof" onClick={() => setMenu(false)}>Proof</a><a href="#process" onClick={() => setMenu(false)}>Process</a><a href="#faq" onClick={() => setMenu(false)}>FAQs</a><button onClick={onSurvey} className="button-clay">Free site survey <ArrowRight size={16} /></button></div>}</header> }

function Hero({ onSurvey }: { onSurvey: () => void }) { const [winter, setWinter] = useState(false); return <section id="top" className="hero"><div className="hero-copy"><p className="eyebrow text-accent">Glasgow · Bearsden · Newton Mearns</p><h1>Bespoke patios &amp; landscaping <em>engineered</em> for Glasgow weather.</h1><p className="hero-sub">Eliminate waterlogged lawns with BS7533-compliant deep sub-base drainage. Installed year-round across Greater Glasgow.</p><div className="hero-actions"><button onClick={onSurvey} className="button-clay">Get your free fixed-price site survey <ArrowRight size={17} /></button><a href="#proof" className="button-outline">See the proof <ChevronDown size={17} /></a></div><p className="microcopy">No pushy sales <span>·</span> Guaranteed start date <span>·</span> Valid 12 months</p></div><div className="hero-visual"><div className="season-switch"><span className={!winter ? 'active' : ''}>Summer</span><button onClick={() => setWinter(!winter)} aria-label="Toggle season"><motion.span animate={{ x: winter ? 24 : 0 }} /></button><span className={winter ? 'active' : ''}>Winter</span></div><motion.div className="hero-image" animate={{ backgroundPosition: winter ? '60% center' : 'center' }}><div className="image-caption"><AnimatePresence mode="wait"><motion.div key={winter ? 'winter' : 'summer'} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}><p className="eyebrow text-accent">{winter ? 'Winter workflow' : 'Outdoor living'}</p><h2>{winter ? 'Heated & lighted hardscape' : 'Summer outdoor living'}</h2><p>{winter ? 'Keep the garden working after dark, whatever the forecast.' : 'Quietly detailed spaces, built for long Scottish evenings.'}</p></motion.div></AnimatePresence></div></motion.div></div><div className="trust-strip"><span><Star size={15} fill="currentColor" /> 5.0 Google rating <b>(128 reviews)</b></span><span><ShieldCheck size={16} /> Marshall&apos;s approved installer</span><span><Hammer size={16} /> 10-year structural guarantee</span></div></section> }

function Proof() { const [pos, setPos] = useState(51); const ref = useRef<HTMLDivElement>(null); const move = (e: React.PointerEvent) => { if (!ref.current) return; const r = ref.current.getBoundingClientRect(); setPos(Math.max(3, Math.min(97, ((e.clientX - r.left) / r.width) * 100))) }; return <section id="proof" className="section proof-section"><div className="section-intro"><p className="eyebrow">Proof, not promises</p><h2>Turn the wettest corner<br /><em>into the best one.</em></h2><p>Drainage is not an afterthought. It&apos;s the part of the build you never see — and the reason your patio still works after a week of Scottish rain.</p></div><div ref={ref} onPointerMove={move} className="compare" aria-label="Before and after garden comparison slider"><img src="/images/garden-after.png" alt="Finished porcelain patio with perimeter drainage" /><div className="compare-before" style={{ width: `${pos}%` }}><img src="/images/garden-before.png" alt="Waterlogged clay garden before landscaping" /></div><div className="compare-handle" style={{ left: `${pos}%` }}><span>Drag</span><div /></div><span className="compare-label before">Before</span><span className="compare-label after">After</span><div className="metric"><Droplets size={18} /><strong>100%</strong><span>sub-surface water mitigation</span></div></div><p className="slider-note">Drag to reveal · use ← → after selecting the image</p></section> }

function Process() { return <section id="process" className="section process-section"><div className="section-intro"><p className="eyebrow">The Arden method</p><h2>Built like a small<br /><em>piece of architecture.</em></h2></div><div className="process-grid">{[['01','Survey & levels','We map falls, thresholds and the water table before a single slab is ordered.'],['02','Excavate & engineer','Clay out. Geotextile in. Deep MOT Type 1 sub-base compacted for the load and the rainfall.'],['03','Lay & hand over','Precision porcelain, quiet drainage details and a site left cleaner than we found it.']].map(([n,t,d]) => <article key={n}><span className="process-number">{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="testimonial"><div className="stars">★★★★★</div><blockquote>&quot;The difference after the first proper downpour was remarkable. Every detail feels considered.&quot;</blockquote><p>— Provisional homeowner testimonial · Bearsden</p></div></section> }

function FAQ() { const [open, setOpen] = useState(0); return <section id="faq" className="section faq-section"><div className="faq-heading"><p className="eyebrow">Straight answers</p><h2>Good questions deserve<br /><em>proper answers.</em></h2></div><div className="faq-list">{faqs.map(([q,a], i) => <div className="faq-item" key={q}><button onClick={() => setOpen(open === i ? -1 : i)} aria-expanded={open === i}><span>{q}</span><ChevronDown className={open === i ? 'rotate-180' : ''} size={20} /></button><AnimatePresence initial={false}>{open === i && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="faq-answer"><p>{a}</p></motion.div>}</AnimatePresence></div>)}</div></section> }

export default function LandingPage() { const [survey, setSurvey] = useState(false); const [sticky, setSticky] = useState(false); useEffect(() => { const onScroll = () => setSticky(window.scrollY > window.innerHeight * .75); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, []); return <><Header onSurvey={() => setSurvey(true)} /><main><Hero onSurvey={() => setSurvey(true)} /><Proof /><section className="offseason"><div><p className="eyebrow text-accent">Winter bookings now open</p><h2>Beat the 12-week spring backlog.</h2><p>Lock in current material prices and book winter hardscaping while the calendar is clear.</p></div><button onClick={() => setSurvey(true)} className="button-light">Reserve your survey <ArrowRight size={17} /></button></section><Process /><FAQ /></main><footer><div className="wordmark"><span className="wordmark-mark">A</span><span>Arden<span className="text-accent"> / </span>Works<small>LANDSCAPE ENGINEERING</small></span></div><div><p>Provisional contact details</p><a href="tel:+441410000000">0141 000 0000</a><br /><a href="mailto:hello@ardenworks.example">hello@ardenworks.example</a></div><div><p>Serving Greater Glasgow</p><p>Bearsden · Newton Mearns<br />Clarkston · Giffnock</p></div></footer><AnimatePresence>{sticky && <motion.div initial={{ y: 100 }} animate={{ y: 0 }} exit={{ y: 100 }} className="sticky-cta"><span><b>Ready to make it work?</b><small>Fixed-price survey, no pressure.</small></span><button onClick={() => setSurvey(true)} className="button-clay">Get started <ArrowRight size={16} /></button></motion.div>}</AnimatePresence><SurveyDialog open={survey} onClose={() => setSurvey(false)} /></> }
        
